# 📚 **NumPy, Pandas, Matplotlib, and Seaborn Practice Questions**
---
This notebook contains four sets of practice questions covering NumPy, Pandas, Matplotlib, and Seaborn. Complete the tasks below and run the respective cells.

## 🧠 **Question 1: NumPy Array Manipulation**
1. Create a 1D NumPy array with integers from **1 to 24**.  
2. Reshape the array into a **4x6 matrix**.  
3. Extract the **third row** and **second column** from the reshaped array.  
4. Transpose the matrix and display the result.

In [1]:
import numpy as np

In [10]:
# Solution for Question 1
import numpy as np

# Your code here
data =np.arange(1,25)
data.reshape(4,6)
reshaped_array = data.reshape(4, 6)
third_row = reshaped_array[2, :] 
second_column = reshaped_array[:, 1]
transposed_array = reshaped_array.T
transposed_array



array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 🧠 **Question 2: Array Element Extraction**
1. Create a **5x5 NumPy array** with random integers between **10 and 100**.  
2. Extract all the **even numbers** from the array.  
3. Replace all numbers **greater than 50** with **0**.  
4. Extract the diagonal elements of the array.

In [25]:
# Solution for Question 2
import numpy as np

# Your code here
array = np.random.randint(10, 101, size=(5, 5))
even_numbers = array[array % 2 == 0]
array[array > 50] = 0
diagonal_elements = np.diagonal(array)




In [26]:
diagonal_elements

array([ 0,  0,  0, 17,  0], dtype=int32)

In [27]:
array

array([[ 0,  0, 26, 22,  0],
       [49,  0,  0, 41,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0, 17, 16],
       [ 0, 14,  0,  0,  0]], dtype=int32)

## 🧠 **Question 3: DataFrame Creation and Operations (Pandas)**
1. Create a Pandas DataFrame containing the following data:

| Student_ID | Name   | Subject | Marks |
|------------|--------|---------|-------|
| 1          | Alice  | Math    | 88    |
| 2          | Bob    | Science | 75    |
| 3          | Carol  | History | 92    |
| 4          | David  | Math    | 85    |
| 5          | Eva    | Science | 90    |

2. Find the **average marks** for each subject.  
3. Add a new column named **Grade** based on the marks:
- Marks ≥ 90 → A
- Marks ≥ 80 → B
- Marks ≥ 70 → C
- Else → D

In [28]:
# Solution for Question 3
import pandas as pd

# Your code here

In [29]:
data = {
    "Student_ID": [1, 2, 3, 4, 5],
    "Name": ["Alice", "Bob", "Carol", "David", "Eve"],
    "Subject": ["Math", "Science", "History", "Math", "Science"],
    "Marks": [88, 75, 92, 85, 90]
}

df = pd.DataFrame(data)

In [32]:
df

Student_ID   Name  Subject  Marks
0           1  Alice     Math     88
1           2    Bob  Science     75
2           3  Carol  History     92
3           4  David     Math     85
4           5    Eve  Science     90

Student_ID   Name  Subject  Marks
0           1  Alice     Math     88
1           2    Bob  Science     75
2           3  Carol  History     92
3           4  David     Math     85
4           5    Eve  Science     90

## 🧠 **Question 4: Dataset Analysis (Pandas, Matplotlib, Seaborn)**
Use the dataset `diabetes.csv` and perform the following tasks:

1. Display the **BMI** and **Blood Pressure** for samples with **index ranging from 20 to 40**.  
2. Find how many patients have **BMI > 30**.  
3. Find the **mean and standard deviation** of the **Glucose** levels.  
4. Plot a **boxplot** for the column **Insulin**.  
5. Create a **heatmap** showing the correlation between the numerical columns in the dataset.

In [ ]:
# Solution for Question 4
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Your code here